name: IgniteLife
favicon: null
layout_spectrum: 0.10902718966826797
typography_spectrum: 0.9563826357480139
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6a3342'
    - '#0f0100'
    - '#ce8c66'
    - '#f8ddc8'
    - '#ca2119'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.3800713249947876
purpose: []
