name: IgniteLife
favicon: null
layout_spectrum: 0.10902718966826797
typography_spectrum: 0.9563826357480139
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000405'
    - '#00457c'
    - '#e25400'
    - '#9a0000'
    - '#fefb86'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.3800713249947876
purpose: []
