name: IgniteLife
favicon: null
layout_spectrum: 0.10902718966826797
typography_spectrum: 0.9563826357480139
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.473438375396654
  lightness: 0.2862241992261261
  saturation: 0.48045258061029017
  rhythmicContrast: 0.3800713249947876
purpose: []
